# Bake the three poses + the tally glyphs to panel bitmaps -> gen\panel.h (for src\leonard.c)
#   python tools\gen_panel.py [W H]          (default 800 400)
# Each pose is drawn crisply in Consolas at CW x CH px per cell, cropped to the art, scaled to fit the panel above
# a free strip at the bottom (BAND, where the session tally goes) and centred: the scaled-down look.
# The tally is ASCII too: a '|' glyph per session and a '/' glyph stretched across four of them for the fifth.
# Eye sockets (from gen_sprites.EYES, in cells) are mapped to panel pixels.
import sys
from PIL import Image, ImageDraw, ImageFont
import gen_sprites as gs
import paths as P

PW, PH = (int(sys.argv[1]), int(sys.argv[2])) if len(sys.argv) >= 3 else (800, 400)
MARGIN = 4
BAND = round(PH * 0.09)            # free strip at the bottom for the session tally
GAIN = 1.7                         # thin strokes read fainter on the bigger panel; 480x320 stays as approved
CW, CH = 11, 22
font = ImageFont.truetype("consola.ttf", 20)

def bake(rows, eyes):
    cells = [(c, r) for r, l in enumerate(rows) for c, ch in enumerate(l) if ch != " "]
    c0, c1 = min(c for c, _ in cells), max(c for c, _ in cells) + 1
    r0, r1 = min(r for _, r in cells), max(r for _, r in cells) + 1
    big = Image.new("L", ((c1 - c0) * CW, (r1 - r0) * CH))
    d = ImageDraw.Draw(big)
    for r in range(r0, r1):
        for c, ch in enumerate(rows[r]):
            if ch != " ": d.text(((c - c0) * CW, (r - r0) * CH), ch, font=font, fill=235)
    s = min((PW - 2 * MARGIN) / big.width, (PH - 2 * MARGIN - BAND) / big.height)
    small = big.resize((round(big.width * s), round(big.height * s)), Image.LANCZOS)
    ox, oy = (PW - small.width) // 2, MARGIN + (PH - 2 * MARGIN - BAND - small.height) // 2
    if PW > 480: small = small.point(lambda v: min(255, int(v * GAIN)))
    img = Image.new("L", (PW, PH)); img.paste(small, (ox, oy))
    peyes = [(ox + (c + 0.5 - c0) * CW * s, oy + (r + 0.5 - r0) * CH * s, wx * CW * s, wy * CH * s)
             for c, r, wx, wy in eyes]
    return img, peyes

# ---- tally glyphs: ASCII '|' and '/' rendered in the same font, scaled down the same way
TH = max(8, round(BAND * 0.62))                  # glyph height
TCW = max(4, round(TH * 0.55))                   # one monospace cell
TY = PH - MARGIN - BAND + (BAND - TH) // 2       # top of the tally row
bigf = ImageFont.truetype("consola.ttf", 200)

def glyph(ch, w, h):
    im = Image.new("L", (300, 300)); d = ImageDraw.Draw(im)
    d.text((50, 0), ch, font=bigf, fill=235)
    ink = im.crop(im.getbbox())                                  # the character's own strokes, tight
    if ch == "|":                                                # keep the bar's proportions, centred in its cell
        sw = max(1, round(ink.width * h / ink.height))
        cell = Image.new("L", (w, h)); cell.paste(ink.resize((sw, h), Image.LANCZOS), ((w - sw) // 2, 0)); out = cell
    else:
        out = ink.resize((w, h), Image.LANCZOS)                  # the slash stretched across the group
    if PW > 480: out = out.point(lambda v: min(255, int(v * GAIN)))
    return out

bar = glyph("|", TCW, TH)
# the strike: one thin diagonal at the same stroke weight as the '|' characters, across the four bars
# (tried: a staircase of small '/' and an ASCII '_,-'' line - neither read as a crossed tally at this size)
SW, SH = 4 * TCW + TCW // 2, TH + 2
_big = Image.new("L", (SW * 4, SH * 4)); ImageDraw.Draw(_big).line((0, SH * 4 - 4, SW * 4, 4), fill=235, width=7)
strike = _big.resize((SW, SH), Image.LANCZOS)
if PW > 480: strike = strike.point(lambda v: min(255, int(v * GAIN)))
def carray(name, im):
    data = im.tobytes()
    return f"static const unsigned char {name}[{len(data)}] = {{" + ",".join(str(b) for b in data) + "};\n"

with open(P.GEN / "panel.h", "w") as f:
    f.write("/* generated by gen_panel.py - do not edit */\n#define PANEL_W %d\n#define PANEL_H %d\n" % (PW, PH))
    for name, rows in (("LEFT", gs.left), ("FRONT", gs.front), ("RIGHT", gs.right)):
        img, peyes = bake(rows, gs.EYES[name])
        img.save(P.BUILD / f"panel_{name.lower()}.png")
        data = img.tobytes()
        f.write(f"static const unsigned char PAN_{name}[{PW * PH}] = {{\n")
        for i in range(0, len(data), 32):
            f.write(",".join(str(b) for b in data[i:i + 32]) + ",\n")
        f.write("};\n")
        f.write(f"static const float PEYE_{name}[2][4] = {{" +
                ", ".join("{%.1f, %.1f, %.2f, %.2f}" % e for e in peyes) + "};\n")
        print(name, ["(%.0f,%.0f r%.1fx%.1f)" % e for e in peyes])
    f.write("/* session tally: ASCII glyphs, a row centred in the bottom strip */\n")
    f.write("#define TALLY_H %d\n#define TALLY_CW %d\n#define TALLY_Y %d\n#define TALLY_SW %d\n#define TALLY_SH %d\n" % (TH, TCW, TY, SW, SH))
    f.write(carray("TALLY_BAR", bar))
    f.write(carray("TALLY_STRIKE", strike))
    print("tally glyph %dx%d px, cell %d px, row at y=%d, strike %dx%d" % (TCW, TH, TCW, TY, SW, SH))
