# Export the three avatar poses + eye sockets to sprites.h for impure_avatar.c
#   python gen_sprites.py
# right = impure.txt (the transcribed base art, faces right), left = its mirror,
# centre = view_front.txt (build_front.py). Eye entries are the socket centres
# (col,row) and half-sizes in cells; the LED glow fills the empty cells there.
import os
from make_views import mirror

import paths as P

def read(name):
    return open(P.ART / name).read().splitlines()

right = read("impure.txt")
right = [r.split("        i      m")[0].rstrip() for r in right]     # drop the "impure" tag
W = max(map(len, right))
left = [mirror(r.ljust(W)).rstrip() for r in right]
front = read("view_front.txt")

# (col, row, half-width, half-height) per eye; the side views show the far eye small
EYE_R = [(59, 21, 3.4, 1.8), (83.5, 22.7, 1.2, 1.4)]
EYES = {
    "LEFT":  [(W - 1 - c, r, wx, wy) for c, r, wx, wy in EYE_R],
    "FRONT": [(61.3, 18.3, 1.7, 1.9), (89.2, 18.0, 1.7, 1.7)],
    "RIGHT": EYE_R,
}

def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

with open(P.GEN / "sprites.h", "w") as f:
    f.write("/* generated by gen_sprites.py - do not edit */\n")
    for name, rows in (("LEFT", left), ("FRONT", front), ("RIGHT", right)):
        while rows and not rows[-1].strip(): rows = rows[:-1]
        f.write(f"static const char *SPR_{name}[] = {{\n")
        for r in rows: f.write("    " + cstr(r) + ",\n")
        f.write("    0 };\n")
        f.write(f"static const float EYE_{name}[2][4] = {{" +
                ", ".join("{%g, %g, %g, %g}" % e for e in EYES[name]) + "};\n")
print("ok", W, len(right), len(front))
