# Export the three avatar poses + eye sockets to gen\sprites.h (for the terminal avatar) and for gen_panel.py.
#   python tools\gen_sprites.py
# The art is plain text and IS the source: edit assets\art\right.txt and assets\art\front.txt by hand.
#   right.txt  the head turned to the right (the left pose is generated as its mirror image)
#   front.txt  the head facing front
# Eye entries below are the socket centres (col,row) and half-sizes in cells; the LED glow fills the empty cells there.
import paths as P

# mirror image of a line of art: reverse it, and swap the characters whose slant / bracket direction flips
SWAP = {"/": "\\", "\\": "/", "(": ")", ")": "(", "[": "]", "]": "[", "<": ">", ">": "<",
        "`": "'", "L": "J", "J": "L", "{": "}", "}": "{", "7": "r", "r": "7"}

def mirror(s):
    return "".join(SWAP.get(c, c) for c in reversed(s))

def read(name):
    return [r.rstrip() for r in open(P.ART / name).read().splitlines()]

right = read("right.txt")
W = max(map(len, right))
left = [mirror(r.ljust(W)).rstrip() for r in right]
front = read("front.txt")

# (col, row, half-width, half-height) per eye; the side views show the far eye small
EYE_R = [(59, 21, 3.4, 1.8), (83.5, 22.7, 1.2, 1.4)]
EYES = {
    "LEFT":  [(W - 1 - c, r, wx, wy) for c, r, wx, wy in EYE_R],
    "FRONT": [(61.3, 18.3, 1.7, 1.9), (89.2, 18.0, 1.7, 1.7)],
    "RIGHT": EYE_R,
}

def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

if __name__ == "__main__" or True:          # also runs when gen_panel.py imports this module
    with open(P.GEN / "sprites.h", "w") as f:
        f.write("/* generated by gen_sprites.py - do not edit */\n")
        for name, rows in (("LEFT", left), ("FRONT", front), ("RIGHT", right)):
            while rows and not rows[-1].strip(): rows = rows[:-1]
            f.write(f"static const char *SPR_{name}[] = {{\n")
            for r in rows: f.write("    " + cstr(r) + ",\n")
            f.write("    0 };\n")
            f.write(f"static const float EYE_{name}[2][4] = {{" +
                    ", ".join("{%g, %g, %g, %g}" % e for e in EYES[name]) + "};\n")
    print("ok", W, len(right), len(front))
