# Bake the three poses to panel bitmaps (default 800x480 = the 5" panel; pass W H for another size, e.g. 480 320) -> panel.h (for impure_panel.c)
#   python gen_panel.py
# Each pose is drawn crisply in Consolas at CW x CH px per cell, cropped to the
# art, scaled to fit the panel (LANCZOS) and centred: the scaled-down look.
# Eye sockets (from gen_sprites.EYES, in cells) are mapped to panel pixels.
import os, sys
from PIL import Image, ImageDraw, ImageFont
import gen_sprites as gs

import paths as P
PW, PH = (int(sys.argv[1]), int(sys.argv[2])) if len(sys.argv) >= 3 else (800, 480)      # python tools\gen_panel.py [W H]
MARGIN = 4
GAIN = 1.7
CW, CH = 11, 22
font = ImageFont.truetype("consola.ttf", 20)

def bake(rows, eyes):
    cells = [(c, r) for r, l in enumerate(rows) for c, ch in enumerate(l) if ch != " "]
    c0, c1 = min(c for c, _ in cells), max(c for c, _ in cells) + 1
    r0, r1 = min(r for _, r in cells), max(r for _, r in cells) + 1
    big = Image.new("L", ((c1 - c0) * CW, (r1 - r0) * CH))
    d = ImageDraw.Draw(big)
    for r in range(r0, r1):
        for c, ch in enumerate(rows[r]):
            if ch != " ": d.text(((c - c0) * CW, (r - r0) * CH), ch, font=font, fill=235)
    s = min((PW - 2 * MARGIN) / big.width, (PH - 2 * MARGIN) / big.height)
    small = big.resize((round(big.width * s), round(big.height * s)), Image.LANCZOS)
    ox, oy = (PW - small.width) // 2, (PH - small.height) // 2
    if PW > 480: small = small.point(lambda v: min(255, int(v * GAIN)))        # thin strokes read fainter on the bigger panel; 480x320 stays as approved
    img = Image.new("L", (PW, PH)); img.paste(small, (ox, oy))
    peyes = [(ox + (c + 0.5 - c0) * CW * s, oy + (r + 0.5 - r0) * CH * s, wx * CW * s, wy * CH * s)
             for c, r, wx, wy in eyes]
    return img, peyes

with open(P.GEN / "panel.h", "w") as f:
    f.write("/* generated by gen_panel.py - do not edit */\n#define PANEL_W %d\n#define PANEL_H %d\n" % (PW, PH))
    for name, rows in (("LEFT", gs.left), ("FRONT", gs.front), ("RIGHT", gs.right)):
        img, peyes = bake(rows, gs.EYES[name])
        img.save(P.BUILD / f"panel_{name.lower()}.png")
        data = img.tobytes()
        f.write(f"static const unsigned char PAN_{name}[{PW * PH}] = {{\n")
        for i in range(0, len(data), 32):
            f.write(",".join(str(b) for b in data[i:i + 32]) + ",\n")
        f.write("};\n")
        f.write(f"static const float PEYE_{name}[2][4] = {{" +
                ", ".join("{%.1f, %.1f, %.2f, %.2f}" % e for e in peyes) + "};\n")
        print(name, ["(%.0f,%.0f r%.1fx%.1f)" % e for e in peyes])
