# Transcribe impure_ref.png character-for-character into impure.c.
# The source is ASCII art at a ~3.92 x 7.89 px cell (measured by Fourier fit).
# Each cell is upscaled, contrast-stretched and matched against every printable
# ASCII glyph with a small position jitter; the best glyph is kept.
import os, sys
import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageOps, ImageFilter

import paths as P
PX, PY = 3.92, 7.89            # source cell pitch (px)
K = 4                          # upscale factor
TW, TH = round(PX * K), round(PY * K)
CHARS = list(" .,:;'`-_~^\"|/\\()[]<>=+*!YVLJjlvi")   # glyphs the art is drawn with
FONT = ImageFont.truetype("consola.ttf", int(TH * 0.92))

def norm(a):
    a = a - a.mean(); n = np.linalg.norm(a); return a / n if n > 1e-6 else a

def glyph(ch):
    im = Image.new("L", (TW * 3, TH * 2)); d = ImageDraw.Draw(im)
    d.text((TW, TH // 2), ch, font=FONT, fill=255)
    bb = Image.new("L", (TW, TH))
    # place by font metrics: cell box = advance width x line height
    l, t, r, b = d.textbbox((TW, TH // 2), "M", font=FONT)
    adv = FONT.getlength(ch) or TW
    box = im.crop((TW, TH // 2 + FONT.getbbox("Mg")[1] - 2, TW + int(adv), TH // 2 + FONT.getbbox("Mg")[1] - 2 + int(TH * 1.0)))
    return np.asarray(box.resize((TW, TH), Image.BILINEAR).filter(ImageFilter.GaussianBlur(1.2)), np.float32) / 255

T = np.stack([glyph(c) for c in CHARS])                 # (G, TH, TW)
Tn = np.stack([norm(t) for t in T]); Tm = T.mean((1, 2))

src = Image.open(P.SOURCE / "impure_ref.png").convert("L")
W, H = src.size
src = ImageOps.autocontrast(src, cutoff=0.3)
big = np.asarray(src.resize((round(W * K), round(H * K)), Image.BICUBIC).filter(ImageFilter.GaussianBlur(1.2)), np.float32) / 255

def transcribe(ox, oy, jit=2):
    cols, rows = int((W - ox) / PX), int((H - oy) / PY)
    out, score = [], 0.0
    for r in range(rows):
        line = ""
        for c in range(cols):
            x0, y0 = round((ox + c * PX) * K), round((oy + r * PY) * K)
            best, bs = " ", 0.0
            cell = big[y0:y0 + TH, x0:x0 + TW]
            if cell.shape != (TH, TW) or cell.max() < 0.25:
                line += " "; continue
            for dy in range(-jit, jit + 1):
                for dx in range(-jit, jit + 1):
                    yy, xx = y0 + dy, x0 + dx
                    if yy < 0 or xx < 0: continue
                    p = big[yy:yy + TH, xx:xx + TW]
                    if p.shape != (TH, TW): continue
                    s = (Tn * norm(p)).sum((1, 2))
                    g = int(s.argmax())
                    if s[g] > bs: bs, best = s[g], CHARS[g]
            if bs < 0.35: best = " "
            line += best; score += bs
        out.append(line.rstrip())
    return out, score

if __name__ == "__main__":
    # fit grid origin on a coarse sweep (no jitter), then transcribe with jitter
    best = None
    for ox in np.arange(0, PX, PX / 4):
        for oy in np.arange(0, PY, PY / 4):
            _, s = transcribe(ox, oy, jit=0)
            if not best or s > best[0]: best = (s, ox, oy)
    _, ox, oy = best
    print(f"grid origin {ox:.2f},{oy:.2f}", file=sys.stderr)
    rows, _ = transcribe(ox, oy)
    while rows and not rows[-1]: rows.pop()
    top = 0
    while rows and not rows[0]: rows.pop(0); top += 1
    open(P.ART / "impure_grid.txt", "w").write(f"{ox} {oy + top * PY}\n")
    # the tag "i m p u r e" (lower right) is letters, not line art: the
    # six marks right of the skull are its letters, in order
    for i, r in enumerate(rows):
        marks = [c for c in range(85, len(r)) if r[c] != " "]
        if len(marks) == 6 and min(b - a for a, b in zip(marks, marks[1:])) >= 4:
            r = list(r)
            for c, ch in zip(marks, "impure"): r[c] = ch
            rows[i] = "".join(r)
    cols = max(len(r) for r in rows)

    def cstr(s): return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    with open(P.GEN / "impure.c", "w") as f:
        f.write(f"""/* impure.c - ASCII ram skull (side view), transcribed from impure_ref.png.
 *   generated by gen_impure.py ({cols}x{len(rows)}); edit the art there, not here.
 *   build:  gcc -O2 -o impure.exe impure.c
 *   run:    impure            (colour)
 *           impure --plain    (plain text)
 */
#include <stdio.h>
#include <string.h>
#ifdef _WIN32
#include <windows.h>
#endif

#define ROWS {len(rows)}
static const char *ART[ROWS] = {{
""")
        for s in rows: f.write("    " + cstr(s) + ",\n")
        f.write("""};

int main(int argc, char **argv) {
    int plain = argc > 1 && !strcmp(argv[1], "--plain");
    if (plain) { for (int r = 0; r < ROWS; r++) puts(ART[r]); return 0; }
#ifdef _WIN32
    { HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE); DWORD md = 0; GetConsoleMode(h, &md); SetConsoleMode(h, md | 0x0004); }
#endif
    printf("\\x1b[38;2;225;225;225m");
    for (int r = 0; r < ROWS; r++) puts(ART[r]);
    printf("\\x1b[0m");
    return 0;
}
""")
    (P.ART / "impure.txt").write_text("\n".join(rows) + "\n", encoding="ascii")
    print(f"impure.txt: {cols}x{len(rows)}")
